version: "3"

services:

  poll:
    build: ./poll
    restart: always
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - poll-tier



  result:
    build: ./result
    restart: always
    ports:
      - "5001:80"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - result-tier



  worker:
    build:
      context: ./worker
      target: builder
    restart: always
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    depends_on:
      - redis
      - db
    networks:
      - back-tier



  redis:
    image: redis
    restart: always
    expose:
      - "6379"
    networks:
      - poll-tier
      - back-tier



  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=poll
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - result-tier
      - back-tier


networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
